name: Minecord
version: Beta 1.4
author: RcExtract
main: com.rcextract.minecord.Minecord
database: true
depend: [RcLib]
commands:
    minecord:
        usage: /<command>
    users:
        usage: /<command>