name: Minecord
version: 1.1.1
author: RcExtract
main: com.rcextract.minecord.Minecord
database: true
depend: [Vault]
commands:
    minecord:
        usage: /<command>
permissions:
    minecord.create-server:
        default: true
        description: Permits a player to create a server.