name: Minecord
version: 1.1.3
author: RcExtract
main: com.rcextract.minecord.bukkitminecord.BukkitMinecord
database: true
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
    minecord:
        usage: /<command>
permissions:
    minecord.create-server:
        default: true
        description: Permits a player to create a server.
    minecord.connect:
        default: false
        description: Permits a command sender to set preferences for connecting to database.